import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthProvider from "./components/AuthProvider";
import Header from "./components/Header";
import "./globals.css";
import type { Metadata } from "next";
import ReduxProvider from "./components/ReduxProvider";

export const metadata: Metadata = {
  title: "testing project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body   >
        <ReduxProvider>
          <ToastContainer />
          <AuthProvider>
            <Header />
            <main className="w-4/5 mx-auto m-2 ">{children}</main>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
